/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Color: (() => {
      const name = "Color";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          r: RecsType.Number,
          g: RecsType.Number,
          b: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Owner: (() => {
      const name = "Owner";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          address: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Permission: (() => {
      const name = "Permission";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          caller_system: RecsType.Number,
          allowed: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Text: (() => {
      const name = "Text";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          string: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Timestamp: (() => {
      const name = "Timestamp";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          created_at: RecsType.Number,
          updated_at: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    PixelType: (() => {
      const name = "PixelType";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          name: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    NeedsAttention: (() => {
      const name = "NeedsAttention";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          value: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    ColorCount: (() => {
      const name = "ColorCount";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          count: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Game: (() => {
      const name = "Game";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          game_id: RecsType.Number,
          state: RecsType.Number,
          player1: RecsType.Number,
          player2: RecsType.Number,
          player1_hash: RecsType.Number,
          player2_hash: RecsType.Number,
          player1_commit: RecsType.Number,
          player2_commit: RecsType.Number,
          started_timestamp: RecsType.Number,
          winner: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Player: (() => {
      const name = "Player";
      return defineComponent(
        world,
        {
          player_id: RecsType.Number,
          wins: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
